# Generated by Django 2.2.12 on 2020-06-10 17:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('feasibility', models.FloatField(default=1)),
                ('events_is_movable', models.BooleanField(default=True)),
                ('events_min_length', models.IntegerField(default=30)),
                ('events_max_length', models.IntegerField(default=90)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('feasibility', models.FloatField(default=1)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.DurationField(default=datetime.timedelta(0, 1800))),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.IntegerField(default=5)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Event')),
            ],
        ),
    ]
