# Generated by Django 2.2.12 on 2020-06-11 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 1800)),
        ),
    ]
