# Generated by Django 2.2.12 on 2020-06-11 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200611_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 600)),
        ),
    ]
