# Generated by Django 2.2.12 on 2020-06-11 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='event_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.Event'),
        ),
    ]
