# Generated by Django 2.2.12 on 2020-06-11 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20200611_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.Project'),
        ),
    ]
