# Generated by Django 2.2.12 on 2020-06-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_task_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='google_calendar_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
