# Generated by Django 2.2.12 on 2020-06-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_auto_20200629_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.FloatField(default=0),
        ),
    ]
