# Generated by Django 2.2.12 on 2020-07-03 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('mysite', '0018_mima'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCreds',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('token', models.CharField(max_length=200)),
                ('refresh_token', models.CharField(max_length=200)),
                ('id_token', models.CharField(max_length=200)),
                ('token_uri', models.CharField(max_length=200)),
                ('client_id', models.CharField(max_length=200)),
                ('client_secret', models.CharField(max_length=200)),
                ('scopes', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='MIMA',
        ),
    ]
