# Generated by Django 2.2.12 on 2020-07-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_googlecreds_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecreds',
            name='id_token',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
