# Generated by Django 2.2.12 on 2020-07-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_auto_20200703_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecreds',
            name='id_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
