# Generated by Django 2.2.12 on 2020-07-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0022_auto_20200703_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecreds',
            name='client_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='googlecreds',
            name='client_secret',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='googlecreds',
            name='expiry',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='googlecreds',
            name='id_token',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='googlecreds',
            name='refresh_token',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='googlecreds',
            name='scopes',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='googlecreds',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='googlecreds',
            name='token_uri',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
