# Generated by Django 2.2.12 on 2020-07-04 10:05

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0023_auto_20200704_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecreds',
            name='creds',
            field=picklefield.fields.PickledObjectField(blank=True, default=None, editable=False, null=True),
        ),
    ]
