# Generated by Django 2.2.12 on 2020-07-06 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0025_auto_20200706_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='order',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='time',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
