# Generated by Django 2.2.12 on 2020-07-15 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0026_auto_20200706_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.Event'),
        ),
    ]
