# Generated by Django 2.2.12 on 2020-08-06 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0028_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='activity_id',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='events_is_movable',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='events_max_length',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='events_min_length',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='feasibility',
        ),
        migrations.RemoveField(
            model_name='event',
            name='active',
        ),
        migrations.RemoveField(
            model_name='event',
            name='feasibility',
        ),
        migrations.RemoveField(
            model_name='project',
            name='active',
        ),
        migrations.RemoveField(
            model_name='project',
            name='order',
        ),
        migrations.RemoveField(
            model_name='task',
            name='active',
        ),
        migrations.RemoveField(
            model_name='task',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='order',
        ),
        migrations.RemoveField(
            model_name='time',
            name='order',
        ),
        migrations.RemoveField(
            model_name='time',
            name='task',
        ),
        migrations.AddField(
            model_name='event',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_prev', to='mysite.Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='prev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_next', to='mysite.Event'),
        ),
        migrations.AddField(
            model_name='time',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='time',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_prev', to='mysite.Time'),
        ),
        migrations.AddField(
            model_name='time',
            name='prev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_next', to='mysite.Time'),
        ),
    ]
