# Generated by Django 2.2.12 on 2020-08-06 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0030_auto_20200806_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Task'),
        ),
    ]
