# Generated by Django 2.2.12 on 2020-08-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0031_time_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='code',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='settings',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='settings',
            name='value',
            field=models.CharField(default='', max_length=200),
        ),
    ]
