# Generated by Django 2.2.12 on 2020-08-07 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0032_auto_20200807_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='google',
        ),
    ]
