# Generated by Django 2.2.12 on 2020-08-07 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0033_remove_settings_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='id',
            field=models.AutoField(auto_created=True, default=8, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
